"""
Dark Knight Phantom SIEM - Alert Models
"""
from django.db import models
from django.utils import timezone
import uuid


class Alert(models.Model):
    """Security Alert generated by detection rules"""
    
    SEVERITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('CRITICAL', 'Critical'),
    ]
    
    STATUS_CHOICES = [
        ('NEW', 'New'),
        ('INVESTIGATING', 'Investigating'),
        ('ACKNOWLEDGED', 'Acknowledged'),
        ('RESOLVED', 'Resolved'),
        ('FALSE_POSITIVE', 'False Positive'),
        ('CLOSED', 'Closed'),
    ]
    
    # Identification
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    alert_id = models.CharField(max_length=50, unique=True, db_index=True)
    
    # Alert Details
    title = models.CharField(max_length=500)
    description = models.TextField()
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, db_index=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='NEW', db_index=True)
    
    # Source Information
    rule_name = models.CharField(max_length=255, blank=True, db_index=True)
    rule_id = models.CharField(max_length=100, blank=True)
    
    # Related Events
    event_ids = models.JSONField(default=list)  # List of related SecurityEvent IDs
    event_count = models.IntegerField(default=1)
    
    # Context
    hostname = models.CharField(max_length=255, db_index=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_name = models.CharField(max_length=255, blank=True, db_index=True)
    
    # Additional Data
    details = models.JSONField(default=dict)  # Full alert details
    raw_events = models.JSONField(default=list)  # Sample of raw events
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    first_seen = models.DateTimeField(db_index=True)
    last_seen = models.DateTimeField(db_index=True)
    
    # Assignment
    assigned_to = models.CharField(max_length=255, blank=True)
    
    # Notes
    notes = models.TextField(blank=True)
    
    class Meta:
        db_table = 'alerts'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['severity', 'status', 'created_at']),
        ]
    
    def __str__(self):
        return f"[{self.severity}] {self.title}"
    
    def save(self, *args, **kwargs):
        if not self.alert_id:
            self.alert_id = f"ALERT-{timezone.now().strftime('%Y%m%d')}-{str(uuid.uuid4())[:8].upper()}"
        super().save(*args, **kwargs)


class AlertComment(models.Model):
    """Comments on alerts for investigation notes"""
    alert = models.ForeignKey(Alert, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'alert_comments'
        ordering = ['created_at']
    
    def __str__(self):
        return f"Comment on {self.alert.alert_id} by {self.author}"



