# Generated by Django 5.2.6 on 2025-12-14 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('rule_type', models.CharField(choices=[('THRESHOLD', 'Threshold - Count exceeds limit'), ('SEQUENCE', 'Sequence - Events in order'), ('PATTERN', 'Pattern - Specific event patterns'), ('CORRELATION', 'Correlation - Multiple related events')], max_length=20)),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication Attacks'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('LATERAL_MOVEMENT', 'Lateral Movement'), ('PERSISTENCE', 'Persistence'), ('DEFENSE_EVASION', 'Defense Evasion'), ('CREDENTIAL_ACCESS', 'Credential Access'), ('DISCOVERY', 'Discovery'), ('EXECUTION', 'Execution'), ('COLLECTION', 'Collection'), ('EXFILTRATION', 'Exfiltration'), ('IMPACT', 'Impact')], max_length=50)),
                ('logic', models.JSONField(help_text='Detection logic configuration')),
                ('mitre_tactic', models.CharField(blank=True, max_length=100)),
                ('mitre_technique', models.CharField(blank=True, max_length=50)),
                ('mitre_subtechnique', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('cooldown_minutes', models.IntegerField(default=15, help_text='Minutes before same alert can trigger again')),
                ('min_confidence', models.IntegerField(default=70, help_text='Minimum confidence score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('total_alerts', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detection_rules',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSuppressionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(help_text='Conditions for suppression')),
                ('enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('reason', models.TextField(help_text='Reason for suppression')),
                ('detection_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.detectionrule')),
            ],
            options={
                'db_table': 'alert_suppression_rules',
            },
        ),
        migrations.CreateModel(
            name='EntityTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('USER', 'User Account'), ('HOST', 'Hostname'), ('SOURCE_IP', 'Source IP'), ('TARGET_USER', 'Target User'), ('PROCESS', 'Process'), ('SERVICE', 'Service')], db_index=True, max_length=20)),
                ('entity_value', models.CharField(db_index=True, max_length=500)),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_counts', models.JSONField(default=dict)),
                ('unique_values', models.JSONField(default=dict)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('last_event_id', models.BigIntegerField(blank=True, null=True)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('event_ids', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'entity_trackers',
                'indexes': [models.Index(fields=['entity_type', 'entity_value', 'window_start'], name='entity_trac_entity__38a283_idx')],
                'unique_together': {('entity_type', 'entity_value', 'hostname', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='DetectionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='NEW', max_length=20)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('target_user', models.CharField(blank=True, max_length=255)),
                ('matched_events', models.JSONField(default=list, help_text='List of event IDs that triggered this alert')),
                ('event_count', models.IntegerField(default=0)),
                ('evidence', models.JSONField(default=dict, help_text='Additional context and evidence')),
                ('confidence', models.IntegerField(default=80)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_event_time', models.DateTimeField(blank=True, null=True)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionrule')),
            ],
            options={
                'db_table': 'detection_alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='detection_a_status_270534_idx'), models.Index(fields=['triggered_at', 'status'], name='detection_a_trigger_3e53a0_idx')],
            },
        ),
    ]
