# Generated by Django 5.2.6 on 2025-12-13 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('os_type', models.CharField(choices=[('WINDOWS_10', 'Windows 10'), ('WINDOWS_11', 'Windows 11'), ('WINDOWS_SERVER_2016', 'Windows Server 2016'), ('WINDOWS_SERVER_2019', 'Windows Server 2019'), ('WINDOWS_SERVER_2022', 'Windows Server 2022'), ('WINDOWS_SERVER_2025', 'Windows Server 2025'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('os_build', models.CharField(blank=True, max_length=50)),
                ('architecture', models.CharField(default='x64', max_length=20)),
                ('server_role', models.CharField(choices=[('WORKSTATION', 'Workstation'), ('MEMBER_SERVER', 'Member Server'), ('DOMAIN_CONTROLLER', 'Domain Controller'), ('DNS_SERVER', 'DNS Server'), ('DHCP_SERVER', 'DHCP Server'), ('FILE_SERVER', 'File Server'), ('WEB_SERVER', 'Web Server (IIS)'), ('CERTIFICATE_AUTHORITY', 'Certificate Authority'), ('HYPER_V_HOST', 'Hyper-V Host'), ('OTHER', 'Other')], default='WORKSTATION', max_length=50)),
                ('is_domain_controller', models.BooleanField(default=False)),
                ('agent_version', models.CharField(max_length=20)),
                ('install_date', models.DateTimeField(auto_now_add=True)),
                ('last_config_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('events_sent_total', models.BigIntegerField(default=0)),
                ('events_sent_today', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled_channels', models.JSONField(blank=True, default=list)),
                ('collection_interval', models.IntegerField(default=10)),
                ('batch_size', models.IntegerField(default=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='AgentLogChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('default_filter', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agent_log_channels',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('UPDATE_CONFIG', 'Update Configuration'), ('RESTART', 'Restart Agent'), ('UPDATE_CHANNELS', 'Update Log Channels'), ('COLLECT_NOW', 'Force Collection'), ('STOP', 'Stop Agent'), ('START', 'Start Agent')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('events_in_queue', models.IntegerField(default=0)),
                ('events_sent', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('is_healthy', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
    ]
