# Generated by Django 5.2.6 on 2025-12-13 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'query_history',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'saved_queries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
